### ISSUE TITLE
add support for taking filters as an input

### ISSUE THREAD

**Issue by hkang1** [hkang1/hermes#49]
- also add support for setting filters after chart has instantiated

**Comment by trentwatt** [comment]
This is something I could possibly take on.

Any thoughts @hkang1 on how to approach?

**Comment by trentwatt** [comment]
What is the desired API? 

`setFilters(Hermes.Filter[])`.

`addFilters(Hermes.Filter[])`.

`resetFilters()`

Do merge and update like from user interactions?

Do we want to apply regardless of whether it's above the threshold interaction supplied filters? Or does that cause problems?

**Comment by hkang1** [comment]
> What is the desired API? 
> 
> `setFilters(Hermes.Filter[])`.
> 
> `addFilters(Hermes.Filter[])`.
> 
> `resetFilters()`
> 
Yeah those three actions sound reasonable. Maybe Hermes.Filters as an input instead so we also know which dimension to apply the filters. 

One additional way to add might be to take Filters during Hermes initialization, which would be useful if the dev wanted to build a chart with filters pre applied in one go. 

> Do merge and update like from user interactions?
> 
Yeah. There is an update routine that "cleans up" filters. Specifically it removes 0-sized filters and also merges overlapping filters within the same dimension. But mimicking user interactions makes sense to me. 

> Do we want to apply regardless of whether it's below the threshold required for user-interaction-supplied filters? Or does that cause problems, and we should require threshold?

Good question... my initial reaction is that it's probably best to mimick the user interactions, which translates to following the threshold rules.

**Comment by hkang1** [comment]
`removeFilters()` could be a useful one too, but referencing the exact filter to remove could be a bit tricky. Would need the dimension key and the index of the filter. e.g. removeFilter('accuracy', 1) would remove the 2nd filter from the `accuracy` dimension.

**Comment by hkang1** [comment]
resolved with [PR 114](https://github.com/hkang1/hermes/pull/114)
