### ISSUE TITLE
0 dependencies

### ISSUE THREAD

**Issue by leeoniya** [hkang1/hermes#50]
@hkang1 

this upsets me :rofl: 

https://github.com/hkang1/hermes/blob/94c134fc003fa9f7fa4cdc6fb423c1a717240f62/package.json#L58-L60

you can probably get away with something much cheaper ;)

https://github.com/leeoniya/uPlot/blob/852829eced8a2bc52c58646636f4daa9b42e68cc/src/utils.js#L345-L406

`assign()` here does a deep copying merge, with an `Array.slice()` optimization for arrays of plain values.

(no support for Date, Regex, Map, Set, or other fancy stuff though)

**Comment by hkang1** [comment]
> @hkang1
> 
> this upsets me 🤣
> 
> https://github.com/hkang1/hermes/blob/94c134fc003fa9f7fa4cdc6fb423c1a717240f62/package.json#L58-L60
> 
> you can probably get away with something much cheaper ;)
> 
> https://github.com/leeoniya/uPlot/blob/852829eced8a2bc52c58646636f4daa9b42e68cc/src/utils.js#L345-L406
> 
> `assign()` here does a deep copying merge, with an `Array.slice()` optimization for arrays of plain values.
> 
> (no support for Date, Regex, Map, Set, or other fancy stuff though)

Hey @leeoniya, great to see you here!

ROFL, yeah I know I was lazy, I'll make it 0.
